name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.7-dind
        privileged: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r meepzorp/requirements.txt
          pip install pytest pytest-asyncio

      - name: Run agent tests
        run: |
          COVERAGE_FILE=.coverage.agents \
          pytest meepzorp/agents/*/tests meepzorp/agents/*/*/tests -q --cov=agents

      - name: Run service tests
        run: |
          COVERAGE_FILE=.coverage.services \
          pytest meepzorp/orchestration/tests meepzorp/registry_service/tests -q --cov=orchestration --cov=registry_service

      - name: Combine coverage
        run: |
          coverage combine
          coverage report --fail-under=80

      - name: Build Docker images (no push)
        run: |
          docker compose -f meepzorp/docker-compose.yml build --quiet 